config/routes.rb
Rails.application.routes.draw do

  if Rails.env.production?
    devise_for :users, controllers: { registrations: 'users/registrations' }
  else
    devise_for :users
  end

  resources :personas
  resources :tactics
  resources :pocs
  resources :strategies do |variable|
    resources :tactics, only: [:new]
  end
  resources :objectives do
    resources :strategies, only: [:new]
  end
  resources :value_propositions do
    resources :personas, only: [:new]
  end
  resources :segments do
    resources :personas, only: [:new]
    resources :objectives, only: [:new]
  end
  resources :companies do
    resources :pocs, only: [:new]
    resources :value_propositions, only: [:new]
    resources :segments, only: [:new]
    resources :objectives, only: [:new]
  end
  get 'static_pages/dashboard'

  root 'static_pages#frontpage'

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :pocs, dependent: :destroy
	has_many :value_propositions, dependent: :destroy
	has_many :segments, dependent: :destroy

	validates_presence_of :name
	validates :name, length: {maximum: 60}
end

app/models/objective.rb
class Objective < ActiveRecord::Base
  belongs_to :segment
  has_many :strategies, dependent: :destroy

  validates :title, length: {maximum: 60}
end

app/models/persona.rb
class Persona < ActiveRecord::Base
  belongs_to :value_proposition
  belongs_to :segment
  has_many :clients

  validates :name, length: {maximum: 60}, presence: true

  enum age: [:from_12_to_17, :from_18_to_24, :from_25_to_34, :from_35_to_44, :from_45_to_54, :from_55_to_64, :above_65]
  enum income: [:less_than_20k, :from_20k_to_35k, :from_35k_to_50k, :from_50k_to_75k, :from_75k_to_100k, :from_100k_to_150k, :above_150k]
  enum education: [:less_than_highschool, :high_school_degree, :college_without_degree, :associate_degree, :bachelor_degree, :graduate_degree]
end

app/models/poc.rb
class Poc < ActiveRecord::Base
  belongs_to :company
  has_many :tactics
end

app/models/segment.rb
class Segment < ActiveRecord::Base
  belongs_to :company
  has_many :objectives
  has_many :personas

  validates :name, length: {maximum: 60}, presence: true

  enum growth: [ :na, :neutral, :slow, :high, :booming ]
end

app/models/strategy.rb
class Strategy < ActiveRecord::Base
  belongs_to :objective
  has_many :tactics

  validates :pitch, length: {maximum: 60}
end

app/models/tactic.rb
class Tactic < ActiveRecord::Base
  belongs_to :strategy
  belongs_to :poc

  validates :pitch, length: {maximum: 60}

  enum importance: [:low, :neutral, :medium, :high, :critical]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/value_proposition.rb
class ValueProposition < ActiveRecord::Base
  belongs_to :company
  has_many :personas

  validates :name, length: {maximum: 60}
end

app/controllers/pocs_controller.rb
class PocsController < ApplicationController
  before_action :set_poc, only: [:show, :edit, :update, :destroy]

  # GET /pocs
  # GET /pocs.json
  def index
    @pocs = Poc.all
  end

  # GET /pocs/1
  # GET /pocs/1.json
  def show
  end

  # GET /pocs/new
  def new
    if params[:company_id]
      @company = Company.find(params[:company_id])
      @poc = Poc.new(company_id: @company.id)
    else
      @poc = Poc.new
    end
  end

  # GET /pocs/1/edit
  def edit
  end

  # POST /pocs
  # POST /pocs.json
  def create
    @poc = Poc.new(poc_params)

    respond_to do |format|
      if @poc.save
        format.html { redirect_to @poc, notice: 'Poc was successfully created.' }
        format.json { render :show, status: :created, location: @poc }
      else
        format.html { render :new }
        format.json { render json: @poc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pocs/1
  # PATCH/PUT /pocs/1.json
  def update
    respond_to do |format|
      if @poc.update(poc_params)
        format.html { redirect_to @poc, notice: 'Poc was successfully updated.' }
        format.json { render :show, status: :ok, location: @poc }
      else
        format.html { render :edit }
        format.json { render json: @poc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pocs/1
  # DELETE /pocs/1.json
  def destroy
    @poc.destroy
    respond_to do |format|
      format.html { redirect_to pocs_url, notice: 'Poc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poc
      @poc = Poc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poc_params
      params.require(:poc).permit(:name, :title, :role, :img, :linkedin, :twitter, :telephone, :email, :company_id)
    end
end

app/controllers/tactics_controller.rb
class TacticsController < ApplicationController
  before_action :set_tactic, only: [:show, :edit, :update, :destroy]

  # GET /tactics
  # GET /tactics.json
  def index
    @tactics = Tactic.all
  end

  # GET /tactics/1
  # GET /tactics/1.json
  def show
  end

  # GET /tactics/new
  def new
    if params[:strategy_id]
      @tactic = Tactic.new(strategy_id: params[:strategy_id])
    elsif params[:poc_id]
      @tactic = Tactic.new(poc_id: params[:poc_id])
    else
      @tactic = Tactic.new
    end
  end

  # GET /tactics/1/edit
  def edit
  end

  # POST /tactics
  # POST /tactics.json
  def create
    @tactic = Tactic.new(tactic_params)

    respond_to do |format|
      if @tactic.save
        format.html { redirect_to @tactic, notice: 'Tactic was successfully created.' }
        format.json { render :show, status: :created, location: @tactic }
      else
        format.html { render :new }
        format.json { render json: @tactic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tactics/1
  # PATCH/PUT /tactics/1.json
  def update
    respond_to do |format|
      if @tactic.update(tactic_params)
        format.html { redirect_to @tactic, notice: 'Tactic was successfully updated.' }
        format.json { render :show, status: :ok, location: @tactic }
      else
        format.html { render :edit }
        format.json { render json: @tactic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tactics/1
  # DELETE /tactics/1.json
  def destroy
    @tactic.destroy
    respond_to do |format|
      format.html { redirect_to tactics_url, notice: 'Tactic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tactic
      @tactic = Tactic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tactic_params
      params.require(:tactic).permit(:pitch, :description, :medium, :importance, :frequency, :start, :end, :kpi, :budget, :strategy_id, :poc_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/pocs_helper.rb
module PocsHelper
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/strategies_helper.rb
module StrategiesHelper
end

app/helpers/tactics_helper.rb
module TacticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'shared/head' %>
</head>
<body>
  
  <%= render 'shared/menu' %>

  <div class="container">
    <%= render 'shared/flash' %>

    <%= yield %>
  </div>

  <%= render 'shared/footer' %>

</body>
</html>

app/views/layouts/full_width.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'shared/head' %>
</head>
<body>
  
<%= render 'shared/menu' %>

<div class="container">
	<%= render 'shared/flash' %>
</div>

<%= yield %>

<%= render 'shared/footer' %>

</body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= msg %>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <br>
    <p class="text-center"><a href="/">MissionControl</a> All rights reserved © <%= Time.now.strftime("%Y") %> <span class="glyphicon glyphicon-tree-conifer" aria-hidden="true"></span> A <a href="https://lyketil.com">Lyketil</a> project, powered by Ruby On Rails.</p>
  </div>  
</footer>

app/views/shared/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title>Strategyst</title>

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
<![endif]-->

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.6/handlebars.min.js"></script>
<%= csrf_meta_tags %>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">

	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    <%= link_to "Strategyst", root_path, class: "navbar-brand" %>
	  </div>  <!-- enf of navbar-header -->

	  <div id="navbar" class="collapse navbar-collapse">
		<% if user_signed_in? %>

			<ul class="nav navbar-nav">
				<li><%= link_to "Companies", companies_path, data: { turbolinks: false } %></li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
				  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
				  <ul class="dropdown-menu">
				    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				  </ul>
				</li>
			</ul>

			<!-- <div class="btn-group navbar-btn navbar-right" role="group" aria-label="...">
				<button type="button" class="btn btn-default"><%#= link_to " Segment", new_segment_path %></button>
				<button type="button" class="btn btn-default"><%#= link_to " Persona", new_persona_path %></button>
				<button type="button" class="btn btn-default"><%#= link_to " Objective", new_objective_path %></button>
				<button type="button" class="btn btn-default"><%#= link_to " Strategy", new_strategy_path %></button>
				<button type="button" class="btn btn-default"><%#= link_to " Tactic", new_tactic_path %></button>
			</div> -->

		<% else %>

			<div class="btn-group navbar-btn navbar-right" role="group" aria-label="...">
				<button type="button" class="btn btn-default "><%= link_to " Log In", new_user_session_path %></button>
				<button type="button" class="btn btn-default"><%= link_to " Sign Up", new_user_registration_path %></button>
			</div>

		<% end %>
	  </div>  <!-- end of navbar collapse -->

	</div> <!-- end of container -->
</nav>  <!-- end of nav -->

app/views/shared/_show_model.html.erb
<!-- Use example -->
<%= render partial: "shared/show_model", locals: {model: @segment, columns: 12} %>

<div class="col-md-<%= columns %>">

	<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">
		  <h3 class="panel-title text-center"><%= model.send("#{model.attributes.keys[1]}") %></h3>
		</div>

		<!-- List group -->
		<ul class="list-group">
			<% model.attributes.keys[2..-3].each do |key| %>	
			  <li class="list-group-item"><strong><%= key.titleize %></strong><br> <%= model.send("#{key}") %></li>
			<% end %>
		</ul>

		<div class="panel-body">
		  <%= link_to "Edit", "edit_#{model.class.name.downcase}_path(#{model})", class: "btn btn-sm btn-default pull-right" %>
		</div>
	</div>
	
</div>