config/routes.rb
Rails.application.routes.draw do

  if Rails.env.production?
    devise_for :users, controllers: { registrations: 'users/registrations' }
  else
    devise_for :users
  end

  resources :personas
  resources :tactics
  resources :pocs
  resources :strategies do |variable|
    resources :tactics, only: [:new]
  end
  resources :objectives do
    resources :strategies, only: [:new]
  end
  resources :value_propositions do
    resources :personas, only: [:new]
  end
  resources :segments do
    resources :personas, only: [:new]
    resources :objectives, only: [:new]
  end
  resources :companies do
    resources :pocs, only: [:new]
    resources :value_propositions, only: [:new]
    resources :segments, only: [:new]
    resources :objectives, only: [:new]
  end
  get 'static_pages/dashboard'

  root 'static_pages#frontpage'

end

app/models/segment.rb
class Segment < ActiveRecord::Base
  belongs_to :company
  has_many :objectives
  has_many :personas

  validates :name, length: {maximum: 60}, presence: true

  enum growth: [ :na, :neutral, :slow, :high, :booming ]
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_action :set_segment, only: [:show, :edit, :update, :destroy]

  # GET /segments
  # GET /segments.json
  def index
    @segments = Segment.all
  end

  # GET /segments/1
  # GET /segments/1.json
  def show
    # set_segment by before_action
    @segments = Segment.all

    # raise("error").inspect
    # just to test for our failing getJSON

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @segment }
    end
  end

  # GET /segments/new
  def new
    if params[:company_id]
      @segment = Segment.new(company_id: params[:company_id])
    else
      @segment = Segment.new
    end
  end

  # GET /segments/1/edit
  def edit
  end

  # POST /segments
  # POST /segments.json
  def create
    @segment = Segment.new(segment_params)

    respond_to do |format|
      if @segment.save
        format.html { redirect_to @segment, notice: 'Segment was successfully created.' }
        format.json { render :show, status: :created, location: @segment }
      else
        format.html { render :new }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segments/1
  # PATCH/PUT /segments/1.json
  def update
    respond_to do |format|
      if @segment.update(segment_params)
        format.html { redirect_to @segment, notice: 'Segment was successfully updated.' }
        format.json { render :show, status: :ok, location: @segment }
      else
        format.html { render :edit }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.json
  def destroy
    @segment.destroy
    respond_to do |format|
      format.html { redirect_to segments_url, notice: 'Segment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segment
      @segment = Segment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segment_params
      params.require(:segment).permit(:name, :description, :size, :growth, :company_id)
    end
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_form.html.erb
<%= form_for(@segment) do |f| %>
  <% if @segment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

      <ul>
      <% @segment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well">   

      <div class="input-group">
        <%= f.label :name, class: "input-group-addon" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="input-group">
        <%= f.label :description, class: "input-group-addon" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="input-group">
        <%= f.label :size, class: "input-group-addon" %>
        <%= f.number_field :size, class: "form-control" %>
      </div>
      <div class="input-group">
        <%= f.label :growth %>
        <%= f.select :growth, options_for_select(Segment.growths.collect { |s| [s[0].humanize, s[0]] }) %>
      </div>
      <div class="input-group">
        <%= f.label :company_id %>
        <%= f.collection_select :company_id, Company.order(:name), :id, :name, include_blank: "Nothing selected" %>
      </div>

    </div>
  </div>
</div>

  <div class="actions text-center">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/segments/_segments.html.erb
<div class="row">
  <% segments.each do |segment| %>
  <div class="col-md-4">

    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading animate">
        <h3 class="panel-title text-center"><%= segment.name %></h3>
      </div>

        <!-- List group -->
        <ul class="list-group">
          <li class="list-group-item"><strong>Description</strong><br> <%= segment.description %></li>
          <li class="list-group-item"><strong>Size</strong><br> <%= segment.size %></li>
          <li class="list-group-item"><strong>Growth</strong><br> <%= segment.growth %></li>
          <li class="list-group-item">
            <strong>Personas</strong><br>
            <%= render partial: 'personas/personas', locals: {personas: segment.personas} %>
          </li>
          <li class="list-group-item">
            <strong>Objectives</strong><br>
            <%= render partial: 'objectives/objectives', locals: {objectives: segment.objectives} %>
          </li>
        </ul>

        <div class="panel-body">
          <div class="btn-group pull-right" role="group" aria-label="...">
            <%= link_to "Add Persona", new_segment_persona_path(segment), class: "btn btn-sm btn-default" %>
            <%= link_to "Add Objective", new_segment_objective_path(segment), class: "btn btn-sm btn-default" %>
            <%= link_to "Edit", edit_segment_path(segment), class: "btn btn-sm btn-default" %>
          </div>
        </div>

      </div> <!-- close Default panel contents -->

    </div> <!-- close col-md-4 -->
  <% end %>
</div>   <!-- close row -->

app/views/segments/edit.html.erb
<h1>Editing Segment</h1>

<%= render 'form' %>

<%= link_to 'Show', @segment %> |
<%= link_to 'Back', segments_path %>

app/views/segments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Segments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Size</th>
      <th>Growth</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @segments.each do |segment| %>
      <tr>
        <td><%= segment.name %></td>
        <td><%= segment.description %></td>
        <td><%= segment.size %></td>
        <td><%= segment.growth %></td>
        <td><%= segment.company %></td>
        <td><%= link_to 'Show', segment %></td>
        <td><%= link_to 'Edit', edit_segment_path(segment) %></td>
        <td><%= link_to 'Destroy', segment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Segment', new_segment_path %>

app/views/segments/new.html.erb
<h1 class="text-center">New Segment</h1>

<%= render 'form' %>

<ul class="pager">
	<li><%= link_to 'Back', companies_path %></li>
</ul>

app/views/segments/show.html.erb
<div class="segmentPlaceholder" data-id="<%= @segment.id %>" data-limit="<%= @segments.length %>"></div>
<nav aria-label="...">
  <ul class="pager">
    <li><a href="#" class="previousSegment">Previous</a></li>
    <li><a href="#" class="nextSegment">Next</a></li>
  </ul>
</nav>


<script id="segment-template" type="text/x-handlebars-template">
  <h1>{{name}}</h1>
  <ul class="list-group">
    <li class="list-group-item"><strong>Description</strong><br> {{description}}</li>
    <li class="list-group-item"><strong>Size</strong><br> {{size}}</li>
    <li class="list-group-item"><strong>Growth</strong><br> {{growth}}</li>
  </ul>
</script>


<script>
  Segment.templateSource = $('#segment-template').html();
  Segment.template = Handlebars.compile(Segment.templateSource);

  $placeholder = $('.segmentPlaceholder');
  $id = $placeholder.data('id');
  $maxId = $placeholder.data('limit');

  loadSegment();

  function loadSegment(){
    $.getJSON('/segments/' + $id)
    .success(function(response){
      console.log(response);
      var segment = new Segment(response);
      var segmentHTML = Segment.template(segment);
      $placeholder.html(segmentHTML);
    })
    .error(function(error){
      alert("There was a problem: " + error.statusText);
    });
  }

  $('.previousSegment').on('click', function(event){
    event.preventDefault();
    console.log($id);
    if ($id == 1) {
      return false;
    } else {
      $id -= 1;
      loadSegment();
    }
  })

  $('.nextSegment').on('click', function(event){
    event.preventDefault();
    console.log($id);
    if ($id == $maxId) {
      return false;
    } else {
      $id += 1;
      loadSegment();
    }
  })

</script>



<!-- <p id="notice"><%#= notice %></p>

<p>
  <strong>Name:</strong>
  <%#= @segment.name %>
</p>

<p>
  <strong>Description:</strong>
  <%#= @segment.description %>
</p>

<p>
  <strong>Size:</strong>
  <%#= @segment.size %>
</p>

<p>
  <strong>Growth:</strong>
  <%#= @segment.growth %>
</p>

<p>
  <strong>Company:</strong>
  <%#= link_to @segment.company.name, @segment.company %>
</p>

<%#= link_to 'Edit', edit_segment_path(@segment) %> |
<%#= link_to 'Back', segments_path %> -->