config/routes.rb
Rails.application.routes.draw do

  if Rails.env.production?
    devise_for :users, controllers: { registrations: 'users/registrations' }
  else
    devise_for :users
  end

  resources :personas
  resources :tactics
  resources :pocs
  resources :strategies do |variable|
    resources :tactics, only: [:new]
  end
  resources :objectives do
    resources :strategies, only: [:new]
  end
  resources :value_propositions do
    resources :personas, only: [:new]
  end
  resources :segments do
    resources :personas, only: [:new]
    resources :objectives, only: [:new]
  end
  resources :companies do
    resources :pocs, only: [:new]
    resources :value_propositions, only: [:new]
    resources :segments, only: [:new]
    resources :objectives, only: [:new]
  end
  get 'static_pages/dashboard'

  root 'static_pages#frontpage'

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :pocs, dependent: :destroy
	has_many :value_propositions, dependent: :destroy
	has_many :segments, dependent: :destroy

	validates_presence_of :name
	validates :name, length: {maximum: 60}
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    # for our on-click form
    @company = Company.new

    respond_to do |format|
      format.html
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @segments = @company.segments
    @objectives = @segments.map(&:objectives).flatten
    @strategies = @objectives.map(&:strategies).flatten
    @tactics = @strategies.map(&:tactics).flatten
    @personas = @segments.map(&:personas).flatten

    respond_to do |format|
      format.html { render layout: "full_width" }
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :pitch, :context, :goal, :mission, :vision, :values, :logo, :website, :address)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
<div class="row">
  <div class="col-md-6 offset-3">
    <% if @company.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

        <ul>
        <% @company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>  
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well">
      <div class="input-group">
        <%= f.label :name, class: "input-group-addon" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="input-group">
        <%= f.label :logo, "Logo URL", class: "input-group-addon" %>
        <%= f.text_field :logo, class: "form-control" %>
      </div>
      <div class="input-group">
        <%= f.label :website, "Website URL", class: "input-group-addon" %>
        <%= f.text_field :website, class: "form-control", placeholder: "http://www. ..." %>
      </div>
      <div class="input-group">
        <%= f.label :address, class: "input-group-addon" %>
        <%= f.text_area :address, class: "form-control", rows: 3 %>
      </div>  
    </div>
  </div>
</div>  

  <h3 class="text-center">Setting the scene</h3>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well">  
      <div class="input-group">
        <%= f.label :pitch, class: "input-group-addon" %>
        <%= f.text_area :pitch, class: "form-control", rows: 3, placeholder: "Pitch of their activity, what do they propose and how do they make money?" %>
      </div>
      <div class="input-group">
        <%= f.label :context, class: "input-group-addon" %>
        <%= f.text_area :context, class: "form-control", rows: 4, placeholder: "What's the situation right now?" %>
      </div>
      <div class="input-group">
        <%= f.label :goal, class: "input-group-addon" %>
        <%= f.text_area :goal, class: "form-control", rows: 3, placeholder: "1. First and most important goal\n2. Second goal\n3. Third goal" %>
      </div>
    </div>  
  </div>   
</div>

<h3 class="text-center">Mission Statement</h3>  
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well">    
      <div class="input-group">
        <%= f.label :mission, class: "input-group-addon" %>
        <%= f.text_area :mission, class: "form-control", rows: 3, placeholder: "What's their mission?" %>
      </div>
      <div class="input-group">
        <%= f.label :vision, class: "input-group-addon" %>
        <%= f.text_area :vision, class: "form-control", rows: 3, placeholder: "What's their vision?" %>
      </div>
      <div class="input-group">
        <%= f.label :values, class: "input-group-addon" %>
        <%= f.text_area :values, class: "form-control", rows: 3, placeholder: "What are their core values" %>
      </div>
    </div>
  </div>
</div>    


<div class="actions text-center">
  <%= f.submit class: "btn btn-success center" %>
</div>
<% end %>

app/views/companies/_form_partial.html.erb
<div class="modal fade myModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="gridSystemModalLabel">Create a New Company</h4>
      </div>

      <div class="modal-body">
        <p class="text-center">Fill in all the necessary details about this new company</p>
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>

app/views/companies/edit.html.erb
<h1 class="text-center">Editing "<%= @company.name %>"</h1>

<%= render 'form' %>


<ul class="pager">
	<li><%= link_to 'Show', @company %></li>
	<li><%= link_to 'Back', companies_path %></li>
</ul>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped companies ajax">
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo</th>
      <th>Segments</th>
      <th colspan="2">Edit</th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

<p class="text-center"><%= link_to 'New Company', new_company_path, class: "btn btn-default" %></p>

<!-- This div is used to insert the new company form by jQuery -->
<div class="open-form hidden"></div>


<script>
  // 1. on the click of NEW COMPANY let's show the form
  $('a[href="/companies/new"]').on("click", function(e){
    e.preventDefault();
    var $button = $(this); // gets the jQuery node element for this (clicked  element)

    // toggle the button text
    $button.text(toggleText);
    function toggleText(i, buttonText){
      return buttonText === "Close" ? "Create Company" : "Close";
    }

    $('.open-form').html("<%= j(render 'form') %>").toggleClass('hidden');

    // loads the submit handler after the form has been added to the DOM
    attachSubmitHandler();
  });

  // 2. when click on submit form (only in the case this modal)
  //    2.0. [x] it should hijack the button click and stay right here
  //    2.1. [x] it should send and AJAX post request
  //    2.2. [x] it should add from the server response the new company to the DOM list
  //    2.3. [0] it should close the modal
  function attachSubmitHandler(){
    $('form').on("submit", function(e){
      e.preventDefault();
      var $form = $(this);
      var url = $form.attr("action");  // /companies
      var params = $(this).serialize();  // we want the jQuery object, not just 'this'
      var method = $form.attr("method");  // "post"
      $.ajax({
        url: url,
        data: params,
        method: method,
        dataType: "json"
      })
      .success(function(response){
        var html = '<tr data-id="' + response.id + '">';
        html += '<td><a href="/companies/' + response.id + '" data-turbolinks="false">' + response.name + '</a></td>';
        html += '<td><a href="/companies/' + response.id + '" data-turbolinks="false"><img class="logo" src="' + response.logo + '" alt="Logo"></a></td>';
        html += '<td></td>';
        html += '<td class="editCompany"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></td>';
        html += '</tr>';
        $('tbody').append(html);
        $('.open-form').slideUp(500);
        $('a[href="/companies/new"]').text("Create another Company");
        $('.open-form').toggleClass('hidden').slideDown(500);
        attachAdminButtonHandler();
      })
      .error(function(error){
        // var errorString = handleError(error);
        // alert("There was an issue, try again: " + errorString);
        console.log(error.responseText);
      })
    })
  }

  function handleError(error){
    var errorJSON = JSON.parse(error.responseText);
    var errorString = "";
    for (var key in errorJSON){
      errorString += key + " " + errorJSON[key];
    }
    return errorString;
  }


<!-- This script is for loading the companies table through ajax at page load -->
  $(window).on('load', loadCompanies);

  function loadCompanies(){
    $.getJSON('/companies', setCompanies);
  }

  function setCompanies(response){
    console.log(response);
    html = '';

    $.each(response, function(index, company){
      var segmentsList = function(company){
        return company.segments.map(function(segment, index){
          return segment.name;
        }).join(', ');
      };

      html += `<tr data-id="${company.id}">
      <td><a href="/companies/${company.id}" data-turbolinks="false">${company.name}</a></td>
      <td><img class="logo" src="${company.logo}" alt="Logo"></td>
      <td>${segmentsList(company)}</td>
      <td class="editCompany"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></td>
      </tr>`;
    });

    $('.ajax tbody').html(html);

    attachAdminButtonHandler();
  }

  function attachAdminButtonHandler(){
    $('.editCompany').hover(function(){
      $(this).css("color", "red");
    }, function(){
      $(this).css("color", "black");
    });

    $('.editCompany').on("click", function(){
      $(this).html('<a href="#" class="editCompanyBtn">Edit</a> | <a href="#" class="deleteCompanyBtn">Delete</a>')
      attachEditDeleteBtnHandlers();
    });
  }

  function attachEditDeleteBtnHandlers(){
    $('.editCompanyBtn').on('click', function(event){
      event.preventDefault();
      var btn = $(this);
      console.log('Yo from attachEditDeleteBtnHandlers');
      var companyId = btn.closest('tr').data("id");
      window.location.href = "/companies/" + companyId + "/edit";
      return false;
    });

    $('.deleteCompanyBtn').on('click', function(event){
      event.preventDefault();
      var btn = $(this);
      console.log('Yo from attachEditDeleteBtnHandlers');
      var companyId = btn.closest('tr').data("id");
      confirm("Are you sure you want to destroy this company?");
      $.ajax({
        method: "DELETE",
        url: "/companies/" + companyId,
        dataType: "json"
      })
      .done(deleteSuccess)
      .fail(deleteFail);
    });

    function deleteSuccess(){
      console.log("Deletion! We made it guys.");
      loadCompanies();
    }

    function deleteFail(){
      console.log("Upsss");
    }

  }

</script>

app/views/companies/new.html.erb
<h1 class="text-center">New Company</h1>

<%= render 'form' %>

<ul class="pager">
	<li><%= link_to 'Back', companies_path %></li>
</ul>

app/views/companies/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1><%= link_to @company.name, @company.website %></h1>
      <p>
        <strong><%= simple_format @company.pitch %></strong>
      </p>
      <address>
      <%= simple_format @company.address %>
      </address>
    </div>
    <div class="col-md-4">
      <%= image_tag @company.logo, class: "logo pull-right" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-camera-retro" aria-hidden="true"></i> Context</h3>
        </div>
        <div class="panel-body">
          <%= simple_format @company.context %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-crosshairs" aria-hidden="true"></i> Goal</h3>
        </div>
        <div class="panel-body">
          <%= simple_format @company.goal %>
        </div>
      </div>
    </div>
  </div>

  <div class="well">
    <div class="row">
      <div class="col-md-4">
        <p>
          <h4>Mission</h4>
          <%= simple_format @company.mission %>
        </p>
      </div>

      <div class="col-md-4">
        <p>
          <h4>Vision</h4>
          <%= simple_format @company.vision %>
        </p>
      </div>

      <div class="col-md-4">
        <p>
          <h4>Values</h4>
          <%= simple_format @company.values %>
        </p>
      </div>
    </div>
  </div>

  <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_company_path(@company) %></button>
  <div class="btn-group" role="group" aria-label="...">
    <button type="button" class="btn btn-default"><%= link_to "Add POC", new_company_poc_path(@company) %></button>
    <button type="button" class="btn btn-default"><%= link_to "Add Value Proposition", new_company_value_proposition_path(@company) %></button>
    <button type="button" class="btn btn-default"><%= link_to "Add Market Segment", new_company_segment_path(@company) %></button>
  </div>

</div> <!-- end of first container -->







<section class="low-accent">
  <div class="container">

    <h3>Value Propositions <span class="badge"><%= @company.value_propositions.count %></span> <a class="add-item" data-target=".myModal"><span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span> Add item</a></h3>
    <%= render partial: 'value_propositions/value_propositions', locals: {value_propositions: @company.value_propositions} %>
  </div>
</section>



<!-- This section uses JQUERY to load segments and personas -->

<section>
  <div class="container">
    <div class="segments">
      <h3>Segments <span class="badge"><%= @company.segments.count %></span></h3>
      <div class="row">
        <% @company.segments.each do |segment| %>
          <div class="col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading animate">
                <h3 class="panel-title text-center" data-segment-id="<%= segment.id %>"><%= segment.name %></h3>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <!-- <%#= render partial: 'segments/segments', locals: {segments: @company.segments} %> -->
    </div> <!-- end of the .segments div   -->

    <div class="personas">
      <h3>Personas <span class="badge"><%= @personas.count %></span></h3>
      <div class="row">
        <% @personas.each do |persona| %>
          <div class="col-md-4">
            <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading animate">
                <h3 class="panel-title text-center" data-persona-id="<%= persona.id %>"><%= persona.name %></h3>
              </div>
              <ul class="list-group" style="display: none;"></ul>
            </div>
          </div>
        <% end %>
      </div>
      <!-- <%#= render partial: 'personas/personas', locals: {personas: @personas} %> -->
    </div>
  </div>
</section>

<section class="low-accent">
  <div class="container">
    <h3>Objectives <span class="badge"><%= @objectives.count %></span></h3>
    <%= render partial: 'objectives/objectives', locals: {objectives: @objectives} %>

    <h3>Strategies <span class="badge"><%= @strategies.count %></span></h3>
    <%= render partial: 'strategies/strategies', locals: {strategies: @strategies} %>

    <h3>Tactics <span class="badge"><%= @tactics.count %></span></h3>
    <%= render partial: 'tactics/tactics', locals: {tactics: @tactics} %>
  </div>
</section>

<section>
  <div class="container">
    <h3>Points of Contact <span class="badge"><%= @company.pocs.count %></span></h3>
    <div class="row">
      <% @company.pocs.each do |poc| %>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="<%= poc.img %>" alt="<%= poc.name %>" class="blurb-image">
            <div class="caption">
              <h3><%= poc.name %></h3>
              <p><span class="label label-info"><%= poc.title %></span> acting as POC <span class="label label-info"><%= poc.role %></span></p>
              <p><i class="fa fa-phone" aria-hidden="true"></i> <%= poc.telephone %><br>
                <i class="fa fa-envelope" aria-hidden="true"></i> <%= poc.email %>
              </p>
              <div class="btn-group btn-group-sm" role="group" aria-label="...">
                <button type="button" class="btn btn-default">
                  <a href="<%= poc.twitter %>"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                </button>
                <button type="button" class="btn btn-default">
                  <a href="<%= poc.linkedin %>"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                </button>
              </div>
              <%= link_to "edit", edit_poc_path(poc), class: "btn btn-sm btn-default pull-right" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

<ul class="pager">
  <li><%= link_to 'Edit Company', edit_company_path(@company) %></li>
  <li><%= link_to 'All Companies', companies_path %></li>
</ul>

<!-- This is a MODAL from BOOTSTRAP supposed to show the EDIT for the relevant element -->
<div class="modal fade myModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
      </div>

      <div class="modal-body">
        Blablabla
      </div>

    </div>
  </div>
</div>

<!-- This is a HANDLEBARS #segment-template used to display information about a SEGMENT -->
<script id="segment-template" type="text/x-handlebars-template">
  <ul class="list-group">
    <li class="list-group-item"><strong>Description</strong><br> {{description}}</li>
    <li class="list-group-item"><strong>Size</strong><br> {{size}}</li>
    <li class="list-group-item"><strong>Growth</strong><br> {{growth}}</li>

    {{#if personas}}
    <li class="list-group-item">
      <strong>Personas</strong><br>
      <div class="personas">
        <div class="row">
        {{#each personas}}
          <div class="col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading animate">
                <h3 class="panel-title text-center" data-persona-id="{{id}}">{{name}}</h3>
              </div>
              <ul class="list-group" style="display: none;"></ul>
            </div>
          </div>
        {{/each}}
        </div>
      </div>
    </li>
    {{/if}}

    {{#if objectives}}
      <li class="list-group-item">
        <strong>Objectives</strong><br>
        <div class="row">
          {{#each objectives}}
            <div class="col-md-4">
              <div class="panel panel-default">
                <div class="panel-heading animate">
                  <h3 class="panel-title text-center">{{title}}</h3>
                </div>
              </div>
            </div>
          {{/each}}
        </div>
      </li>
    {{/if}}
  </ul>
</script>

<!-- CAUTION: PARTIAL APPROACHING -->
<!-- This is a HANDLEBARS #persona-template used to display information about a PERSONA -->
<script id="persona-template" type="text/x-handlebars-template">
  <%= render 'personas/persona_handlebars' %>
</script>