config/routes.rb
Rails.application.routes.draw do

  if Rails.env.production?
    devise_for :users, controllers: { registrations: 'users/registrations' }
  else
    devise_for :users
  end

  resources :personas
  resources :tactics
  resources :pocs
  resources :strategies do |variable|
    resources :tactics, only: [:new]
  end
  resources :objectives do
    resources :strategies, only: [:new]
  end
  resources :value_propositions do
    resources :personas, only: [:new]
  end
  resources :segments do
    resources :personas, only: [:new]
    resources :objectives, only: [:new]
  end
  resources :companies do
    resources :pocs, only: [:new]
    resources :value_propositions, only: [:new]
    resources :segments, only: [:new]
    resources :objectives, only: [:new]
  end
  get 'static_pages/dashboard'

  root 'static_pages#frontpage'

end

app/models/strategy.rb
class Strategy < ActiveRecord::Base
  belongs_to :objective
  has_many :tactics

  validates :pitch, length: {maximum: 60}
end

app/controllers/strategies_controller.rb
class StrategiesController < ApplicationController
  before_action :set_strategy, only: [:show, :edit, :update, :destroy]

  # GET /strategies
  # GET /strategies.json
  def index
    @strategies = Strategy.all
  end

  # GET /strategies/1
  # GET /strategies/1.json
  def show
  end

  # GET /strategies/new
  def new
    @strategy = Strategy.new
  end

  # GET /strategies/1/edit
  def edit
  end

  # POST /strategies
  # POST /strategies.json
  def create
    @strategy = Strategy.new(strategy_params)

    respond_to do |format|
      if @strategy.save
        format.html { redirect_to @strategy, notice: 'Strategy was successfully created.' }
        format.json { render :show, status: :created, location: @strategy }
      else
        format.html { render :new }
        format.json { render json: @strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strategies/1
  # PATCH/PUT /strategies/1.json
  def update
    respond_to do |format|
      if @strategy.update(strategy_params)
        format.html { redirect_to @strategy, notice: 'Strategy was successfully updated.' }
        format.json { render :show, status: :ok, location: @strategy }
      else
        format.html { render :edit }
        format.json { render json: @strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strategies/1
  # DELETE /strategies/1.json
  def destroy
    @strategy.destroy
    respond_to do |format|
      format.html { redirect_to strategies_url, notice: 'Strategy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strategy
      @strategy = Strategy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def strategy_params
      params.require(:strategy).permit(:pitch, :description, :ksf, :objective_id)
    end
end

app/helpers/strategies_helper.rb
module StrategiesHelper
end

app/views/strategies/_form.html.erb
<%= form_for(@strategy) do |f| %>
  <% if @strategy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@strategy.errors.count, "error") %> prohibited this strategy from being saved:</h2>

      <ul>
      <% @strategy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well">
      
      <div class="input-group">
        <%= f.label :pitch, class: "input-group-addon" %>
        <%= f.text_area :pitch, class: "form-control", placeholder: "Strategy 3-second-pitch" %>
      </div>
      <div class="input-group">
        <%= f.label :description, class: "input-group-addon" %>
        <%= f.text_area :description, class: "form-control", placeholder: "Description of this strategy", rows: 5 %>
      </div>
      <div class="input-group">
        <%= f.label :ksf, class: "input-group-addon" %>
        <%= f.text_area :ksf, class: "form-control", placeholder: "1. Key Success Factor 1\n2. Key Success Factor 2\n...", rows: 3 %>
      </div>
      <div class="input-group">
        <%= f.label :objective_id %>
        <%= f.collection_select :objective_id, Objective.order(:specific), :id, :specific, include_blank: "Nothing selected"%>
      </div>

    </div>
  </div>
</div>



  <div class="actions text-center">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/strategies/_strategies.html.erb
<div class="row">
  <% strategies.each do |strategy| %>
    <div class="col-md-4">

      <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading animate">
          <h3 class="panel-title text-center"><%= strategy.pitch %></h3>
        </div>

        <!-- List group -->
        <ul class="list-group">
          <li class="list-group-item"><strong>Objective</strong><br> <%= link_to strategy.objective.specific, strategy.objective %></li>
          <li class="list-group-item"><strong>Description</strong><br> <%= simple_format strategy.description %></li>
          <li class="list-group-item"><strong>Key Success Factors</strong><br> <%= simple_format strategy.ksf %></li>
          <li class="list-group-item"><strong>Tactics</strong> <br>
            <%= render partial: 'tactics/tactics', locals: {tactics: strategy.tactics} %>
          </li>
        </ul>

        <div class="panel-body">


          <div class="btn-group pull-right" role="group" aria-label="...">
            <%= link_to "Add Tactic", new_strategy_tactic_path(strategy), class: "btn btn-sm btn-default" %>
            <%= link_to "Edit", edit_strategy_path(strategy), class: "btn btn-sm btn-default" %>
          </div>
          
        </div>
      </div>

    </div> <!-- close col-md-4 -->
  <% end %>
</div>   <!-- close row -->

app/views/strategies/edit.html.erb
<h1>Editing Strategy</h1>

<%= render 'form' %>

<%= link_to 'Show', @strategy %> |
<%= link_to 'Back', strategies_path %>

app/views/strategies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Strategies</h1>

<table>
  <thead>
    <tr>
      <th>Pitch</th>
      <th>Description</th>
      <th>Ksf</th>
      <th>Objective</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @strategies.each do |strategy| %>
      <tr>
        <td><%= strategy.pitch %></td>
        <td><%= strategy.description %></td>
        <td><%= strategy.ksf %></td>
        <td><%= strategy.objective %></td>
        <td><%= link_to 'Show', strategy %></td>
        <td><%= link_to 'Edit', edit_strategy_path(strategy) %></td>
        <td><%= link_to 'Destroy', strategy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Strategy', new_strategy_path %>

app/views/strategies/new.html.erb
<h1 class="text-center">New Strategy</h1>

<%= render 'form' %>

<ul class="pager">
	<li><%= link_to 'Back', companies_path %></li>
</ul>

app/views/strategies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pitch:</strong>
  <%= @strategy.pitch %>
</p>

<p>
  <strong>Description:</strong>
  <%= @strategy.description %>
</p>

<p>
  <strong>Ksf:</strong>
  <%= @strategy.ksf %>
</p>

<p>
  <strong>Objective:</strong>
  <%= @strategy.objective %>
</p>

<%= link_to 'Edit', edit_strategy_path(@strategy) %> |
<%= link_to 'Back', strategies_path %>